### ISSUE TITLE
1.5.6 版本所有的博客都显示不出来了

### ISSUE THREAD

**Issue by zdRan** [bollnh/hexo-theme-material#696]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

一不小心更新到了1.5.6 结果，所有的博客都显示不出来了。只有博客的连接，点击进去后没有内容。

**Comment by zdRan** [comment]
看了下public 目录下生成的html，确实没有吧md文件里的内容添加进去

**Comment by cubesky** [comment]
@zdRan 您可能需要根据最新的 _config.template.yml 更新您的 _config.yml 设定

**Comment by zdRan** [comment]
@cubesky  我直接用的老的_config.yml 文件

**Comment by AmosHuKe** [comment]
之前也好像出现过这个问题，可能是NodeJS版本问题，尝试换到大于V12小于V14的版本
